vim.o.termguicolors = true
require("nitesh.plugins")
require("nitesh.colors")
require("nitesh.options")
require("nitesh.colorscheme")
require("nitesh.keymaps")
require("nitesh.cmp")
require("nitesh.lsp")
require("nitesh.devicons")
require("nitesh.lualine")
require("nitesh.nvimtree")
require("nitesh.telescope")
require("nitesh.treesitter")
require("nitesh.which-key")
require("nitesh.alpha")
require("nitesh.null-ls")
require("nitesh.gitsigns")
require("nitesh.terminal")
require("nitesh.bufferline")


